name: idb_shim
version: 2.6.0+5
description: indexed_db dart base interface with implementation for native (browser), file (io) and in memory.
homepage: https://github.com/tekartik/idb_shim.dart/tree/master/idb_shim
topics:
  - nosql
  - database

environment:
  sdk: ^3.5.0

dependencies:
  sembast: '>=3.6.0 <5.0.0'
  collection: '>=1.15.0 <3.0.0'
  path: '>=1.8.0 <3.0.0'
  meta: '>=1.3.0 <3.0.0'
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  pub_semver: '>=2.0.0'
  stack_trace: '>=1.10.0'
  logging: '>=1.0.0'
  test: '>=1.16.2'
  dev_build: '>=0.16.2'
  process_run: '>=0.12.0'
  build_runner: '>=1.11.3'
  build_test: '>=1.3.7'
  build_web_compilers: '>=2.16.4'
  yaml: '>=3.0.0'
  lints: '>=1.0.1'

