name: idb_test
description: idb testing
version: 0.3.3
homepage: https://github.com/tekartik/idb_shim.dart/tree/master/idb_test

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  idb_shim: '>=2.0.0-nullsafety.0 <3.0.0'
  meta: '>=1.2.3 <3.0.0'
  sembast:
  test: '>=1.16.0-nullsafety.12'
  collection:
  path:
dev_dependencies:
  lints: '>=1.0.1'
  process_run: '>=0.10.0+1'
  build_runner: '>=1.5.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'

dependency_overrides:
  idb_shim:
    path: ../idb_shim
