name: idb_shim_repo_support
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  process_run: '>=0.10.0'
  pub_semver:
  yaml:
dev_dependencies:
  test: '>=1.0.0'
  dev_build: '>=0.16.2'
  lints: '>=2.1.1'
  path:
